In [6]:
#numpy is a library in python used for arrays, data analyst, etc.
import numpy as np

In [4]:
# Creating an array
a = np.array([2,3,4,1])
print(a)

[2 3 4 1]


In [5]:
# Creating an array using the arange()
b = np.arange(1,11)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
# zeros
z = np.zeros((100,100))
print(z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [9]:
# Creating an array of all 1's
one = np.ones((8,8))
print(one)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [14]:
# Creating an array of random values
ran = np.random.random((5,4)) # 5 rows and 4 columns
print(ran)

[[0.66870907 0.38349585 0.78003305 0.3083537 ]
 [0.26969436 0.32110645 0.2741775  0.22543267]
 [0.48208969 0.25527179 0.19435062 0.95085709]
 [0.87595265 0.69134102 0.95378236 0.46127486]
 [0.86265768 0.81869637 0.46433539 0.47237599]]


Selecting Array Element

In [16]:
slicing = np.array([[7,8],[9,10]])
print(slicing)

[[ 7  8]
 [ 9 10]]


In [17]:
print(slicing[0,1])

8


In [18]:
print(slicing[1,1])

10


Working with Data Frames